name = "eventlogger"
main = "src/index.js"
compatibility_date = "2024-04-03"

[vars]
BASE_URL = "https://eventlogger.aamirakwarali.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "eventlogger-db"
database_id = "46a3bed7-283e-4f1e-accd-01ea05d5fcfc"

# Include templates as text modules
[[rules]]
type = "Text"
globs = ["templates/**/*.html"]
fallthrough = true

# Include CSS as text module
[[rules]]
type = "Text"
globs = ["static/**/*.css"]
fallthrough = true

[observability]
enabled = true
