name = "eventlogger"
main = "app.py"
compatibility_date = "2024-04-03"
compatibility_flags = ["python_workers"]

[vars]
BASE_URL = "https://eventlogger.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "eventlogger-db"
database_id = "46a3bed7-283e-4f1e-accd-01ea05d5fcfc"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "eventlogger-uploads"

[observability]
enabled = true
